COCO_LABELS = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)
OBJECT_LABEL = "object"
ANIMAL_LABEL = "animal"

# animals are ANIMAL_LABEL
# others are OBJECT_LABEL
COCO_TYPE = {
    "person": ANIMAL_LABEL,
    "bicycle": OBJECT_LABEL,
    "car": OBJECT_LABEL,
    "motorcycle": OBJECT_LABEL,
    "airplane": OBJECT_LABEL,
    "bus": OBJECT_LABEL,
    "train": OBJECT_LABEL,
    "truck": OBJECT_LABEL,
    "boat": OBJECT_LABEL,
    "traffic light": OBJECT_LABEL,
    "fire hydrant": OBJECT_LABEL,
    "stop sign": OBJECT_LABEL,
    "parking meter": OBJECT_LABEL,
    "bench": OBJECT_LABEL,
    "bird": ANIMAL_LABEL,
    "cat": ANIMAL_LABEL,
    "dog": ANIMAL_LABEL,
    "horse": ANIMAL_LABEL,
    "sheep": ANIMAL_LABEL,
    "cow": ANIMAL_LABEL,
    "elephant": ANIMAL_LABEL,
    "bear": ANIMAL_LABEL,
    "zebra": ANIMAL_LABEL,
    "giraffe": ANIMAL_LABEL,
    "backpack": OBJECT_LABEL,
    "umbrella": OBJECT_LABEL,
    "handbag": OBJECT_LABEL,
    "tie": OBJECT_LABEL,
    "suitcase": OBJECT_LABEL,
    "frisbee": OBJECT_LABEL,
    "skis": OBJECT_LABEL,
    "snowboard": OBJECT_LABEL,
    "sports ball": OBJECT_LABEL,
    "kite": OBJECT_LABEL,
    "baseball bat": OBJECT_LABEL,
    "baseball glove": OBJECT_LABEL,
    "skateboard": OBJECT_LABEL,
    "surfboard": OBJECT_LABEL,
    "tennis racket": OBJECT_LABEL,
    "bottle": OBJECT_LABEL,
    "wine glass": OBJECT_LABEL,
    "cup": OBJECT_LABEL,
    "fork": OBJECT_LABEL,
    "knife": OBJECT_LABEL,
    "spoon": OBJECT_LABEL,
    "bowl": OBJECT_LABEL,
    "banana": OBJECT_LABEL,
    "apple": OBJECT_LABEL,
    "sandwich": OBJECT_LABEL,
    "orange": OBJECT_LABEL,
    "broccoli": OBJECT_LABEL,
    "carrot": OBJECT_LABEL,
    "hot dog": OBJECT_LABEL,
    "pizza": OBJECT_LABEL,
    "donut": OBJECT_LABEL,
    "cake": OBJECT_LABEL,
    "chair": OBJECT_LABEL,
    "couch": OBJECT_LABEL,
    "potted plant": OBJECT_LABEL,
    "bed": OBJECT_LABEL,
    "dining table": OBJECT_LABEL,
    "toilet": OBJECT_LABEL,
    "tv": OBJECT_LABEL,
    "laptop": OBJECT_LABEL,
    "mouse": OBJECT_LABEL,
    "remote": OBJECT_LABEL,
    "keyboard": OBJECT_LABEL,
    "cell phone": OBJECT_LABEL,
    "microwave": OBJECT_LABEL,
    "oven": OBJECT_LABEL,
    "toaster": OBJECT_LABEL,
    "sink": OBJECT_LABEL,
    "refrigerator": OBJECT_LABEL,
    "book": OBJECT_LABEL,
    "clock": OBJECT_LABEL,
    "vase": OBJECT_LABEL,
    "scissors": OBJECT_LABEL,
    "teddy bear": OBJECT_LABEL,
    "hair drier": OBJECT_LABEL,
    "toothbrush": OBJECT_LABEL,
}


def getlabels2numbers():
    return {label: i for i, label in enumerate(COCO_LABELS)}
